-- Insert into SERVICE_OFFERINGS first
INSERT INTO SERVICE_OFFERINGS (TITLE, DESCRIPTION, PRICE_TEXT, IMAGE_URL, GRADIENT, ICON, MULTIPLIER) 
VALUES 
('Diamond Express', 'Elite white-glove delivery service with personal concierge', '1,500 ETB', 'https://images.unsplash.com/photo-1607082350899-7e105aa886ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'from-purple-600 via-pink-500 to-rose-500', 'Crown', 1.5);

INSERT INTO SERVICE_OFFERINGS (TITLE, DESCRIPTION, PRICE_TEXT, IMAGE_URL, GRADIENT, ICON, MULTIPLIER) 
VALUES 
('Nexus Flash', 'AI-powered instant delivery with smart routing technology', '999 ETB', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'from-blue-500 via-cyan-400 to-teal-400', 'Zap', 1.2);

INSERT INTO SERVICE_OFFERINGS (TITLE, DESCRIPTION, PRICE_TEXT, IMAGE_URL, GRADIENT, ICON, MULTIPLIER) 
VALUES 
('Hyper Speed', 'Lightning-fast 45-minute emergency delivery service', '2,200 ETB', 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'from-orange-500 via-red-500 to-pink-500', 'LightningBolt', 1.8);

-- Now insert features for each service
-- Diamond Express features (ID will be 1)
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (1, '🚗 Personal dedicated courier');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (1, '⏰ 1-hour guaranteed delivery');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (1, '📱 Real-time video tracking');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (1, '🎁 Luxury gift packaging');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (1, '⭐ Premium vehicle service');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (1, '🔒 Insurance up to 50,000 ETB');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (1, '👔 Personal delivery coordinator');

-- Nexus Flash features (ID will be 2)
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (2, '🤖 AI-optimized routes');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (2, '⚡ 90-minute delivery');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (2, '📊 Live analytics dashboard');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (2, '🔔 Smart notifications');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (2, '🛡️ Blockchain security');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (2, '📸 Photo confirmation');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (2, '💬 24/7 chatbot support');

-- Hyper Speed features (ID will be 3)
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (3, '🚀 45-minute guaranteed');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (3, '🎯 Precision timing');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (3, '📱 Live GPS tracking');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (3, '🚨 Emergency priority');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (3, '👥 Multiple couriers');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (3, '📞 Direct driver contact');
INSERT INTO SERVICE_OFFERING_FEATURES (SERVICE_OFFERING_ID, FEATURES) VALUES (3, '⏱️ Time-sensitive handling');


INSERT INTO PRICING_CONFIGURATIONS (BASE_FEE, DISTANCE_RATE_PER_KM, FREE_WEIGHT_LIMIT, ADDITIONAL_WEIGHT_FEE_PER_KG) 
VALUES (80.00, 12.00, 10.00, 8.00);


-- Insert subscription plans
INSERT INTO SUBSCRIPTION_PLANS (NAME, DESCRIPTION, PRICE, PERIOD, AMOUNT, BADGE, GRADIENT, ICON, POPULAR) 
VALUES ('Business Lite', 'Essential tools for small businesses', '1,499', 'per month', '1499', 'Best Value', 'from-orange-400 to-amber-500', 'Star', false);

INSERT INTO SUBSCRIPTION_PLANS (NAME, DESCRIPTION, PRICE, PERIOD, AMOUNT, BADGE, GRADIENT, ICON, POPULAR) 
VALUES ('Startup Scale', 'Perfect for fast-growing startups', '3,500', 'per month', '3500', 'Trending', 'from-blue-500 via-cyan-400 to-teal-400', 'Rocket', true);

INSERT INTO SUBSCRIPTION_PLANS (NAME, DESCRIPTION, PRICE, PERIOD, AMOUNT, BADGE, GRADIENT, ICON, POPULAR) 
VALUES ('Enterprise Pro', 'Ultimate growth suite for scaling businesses', '5,999', 'per month', '5999', 'Most Popular', 'from-purple-600 via-pink-500 to-rose-500', 'Crown', true);

--INSERT INTO SUBSCRIPTION_PLANS (NAME, DESCRIPTION, PRICE, PERIOD, AMOUNT, BADGE, GRADIENT, ICON, POPULAR) 
--VALUES ('Corporate Elite', 'Enterprise-grade solutions for large businesses', '9,999', 'per month', '9999', 'Enterprise', 'from-emerald-500 via-green-400 to-lime-400', 'Building', true);


-- Insert features for Business Lite (ID 1)
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (1, '💰 15% standard discount');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (1, '📞 Priority email support');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (1, '⏰ Same-day delivery');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (1, '📱 Basic tracking');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (1, '👤 Single user account');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (1, '📄 Monthly reports');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (1, '🛡️ Basic insurance');

-- Insert features for Startup Scale (ID 2)
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (2, '⚡ 20% volume discount');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (2, '🎯 Smart routing AI');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (2, '📈 Growth insights');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (2, '🔔 Real-time alerts');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (2, '👥 Team management');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (2, '📊 Performance reports');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (2, '💡 Business advisory');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (2, '🔄 Automated workflows');

-- Insert features for Enterprise Pro (ID 3)
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (3, '⭐ 25% exclusive discount');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (3, '🚀 Dedicated account manager');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (3, '📊 Advanced analytics dashboard');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (3, '🔒 Priority queue always');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (3, '🌍 Global shipping rates');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (3, '💬 24/7 premium support');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (3, '🛡️ Insurance coverage');
INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (3, '📱 Custom mobile app');

-- Insert features for Corporate Elite (ID 4)
--INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (4, '🏢 30% corporate discount');
--INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (4, '🤝 Dedicated support team');
--INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (4, '🔐 Enterprise security');
--INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (4, '📦 Unlimited deliveries');
--INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (4, '🌐 Multi-location management');
--INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (4, '💳 Custom billing options');
--INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (4, '📋 SLA guarantees');
--INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (4, '🎓 Training sessions');
--INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (4, '🔧 API access');
--INSERT INTO SUBSCRIPTION_PLAN_FEATURES (SUBSCRIPTION_PLAN_ID, FEATURES) VALUES (4, '📱 White-label solutions');




INSERT INTO USERS (ACCOUNT_TYPE, ADDRESS, CREATED_AT, EMAIL, FIRSTNAME, LASTNAME, PASSWORD, PHONE_NUMBER, ROLE, UPDATED_AT,email_verified) 
VALUES 

(
    NULL, 
    '456 Admin Street', 
    '2025-12-06 13:54:19.488024', 
    'eyobyobil@gmail.com', 
    'Eyob', 
    'Yobil', 
    '$2a$10$hyImNndyJi.UdyCgYqkmD.UV5.qJDCFZdLYk0TIMCAz7qmFtQMxSK', 
    '0900112233', 
    'ADMIN', 
    NULL,
    true
);